


make IMPLEMENTATION_PATH=crypto_kem/lightsaber/m4f bin/crypto_kem_lightsaber_m4f_test.bin
make IMPLEMENTATION_PATH=crypto_kem/lightsaber/m4f bin/crypto_kem_lightsaber_m4f_speed.bin
make IMPLEMENTATION_PATH=crypto_kem/lightsaber/m4f bin/crypto_kem_lightsaber_m4f_stack.bin

make IMPLEMENTATION_PATH=crypto_kem/saber/m4f bin/crypto_kem_saber_m4f_test.bin
make IMPLEMENTATION_PATH=crypto_kem/saber/m4f bin/crypto_kem_saber_m4f_speed.bin
make IMPLEMENTATION_PATH=crypto_kem/saber/m4f bin/crypto_kem_saber_m4f_stack.bin

make IMPLEMENTATION_PATH=crypto_kem/firesaber/m4f bin/crypto_kem_firesaber_m4f_test.bin
make IMPLEMENTATION_PATH=crypto_kem/firesaber/m4f bin/crypto_kem_firesaber_m4f_speed.bin
make IMPLEMENTATION_PATH=crypto_kem/firesaber/m4f bin/crypto_kem_firesaber_m4f_stack.bin

